# Generated by Django 4.1.3 on 2023-06-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='stock_info',
            fields=[
                ('stock_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('telephone', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('cost', models.FloatField(max_length=255)),
            ],
        ),
    ]
