# Generated by Django 4.1.3 on 2023-06-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_user_id_alter_user_username'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stock_info'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
